### ISSUE TITLE
non-docker installation

### ISSUE THREAD

**Issue by michieitel** [lfaino/LoReAn_Example#3]
Hi
I am faced with issues related to the docker and singularity way of installation (due to non-root restrictions and a restrictive admin - for good reasons by the way).

Can you please provide the lorean.py to be able to run it with self-installed dependencies?

Thanks for assistance
Michael

**Comment by lfaino** [comment]
Hi @michieitel 
it is very complicated to install LoReAn out of docker or singularity. there are many dependency
i would suggest to use one of these options and install syngularity:
1)
https://github.com/sylabs/singularity/issues/1258
2)
https://anaconda.org/conda-forge/singularity

cheers
Luigi

**Comment by michieitel** [comment]
Hey Luigi,

thanks for the fast reply.

I tried for 22344days (felt) using singularity (through conda as suggested, but also as a separate installation with go pre-installation), but failed miserably mostly because of the squashfs-tools, which are necessary for running singularity, however, not included during the installation. Installing singularity and squashfs-tools via conda in the same environment still ends in the error of not recognizing the PATH for squashfs-tools (as already reported by others). I was not able to find a solution without root permission (which I most likely will never get ;-( ).

cheers
Michael

**Comment by lfaino** [comment]
@michieitel 
i can see your problems.
I can suggest to follow the Docker image file and see if you can get all the tools working. But i do not know because for some tools you need some root privileges as well
Cheers
Luigi

**Comment by michieitel** [comment]
Hm. Seems like LoReAn is difficult to install within and outside containers😉

Say I am able to install all dependencies where can I find the lorean.py that is included in the latest version? Is that v2.0?
